[webservers]
web1 ansible_host=web1.company.com ansible_connection=ssh ansible_user=admin ansible_ssh_private_key_file=C:\Users\elmir\Desktop\ansible_config\private_key.pem
web2 ansible_host=web2.company.com ansible_connection=ssh ansible_user=admin ansible_ssh_private_key_file=C:\Users\elmir\Desktop\ansible_config\private_key.pem
web3 ansible_host=web3.company.com ansible_connection=ssh ansible_user=admin ansible_ssh_private_key_file=C:\Users\elmir\Desktop\ansible_config\private_key.pem

[database_servers]
db1 ansible_host=db1.company.com ansible_connection=winrm ansible_user=Administrator ansible_password="{{ vault_db1_password }}"

[django_vms:children]
webservers
