---
- name: Setup Docker on target servers
  hosts: all
  become: true

  tasks:
    - name: Download and install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Ensure Docker service is running and enabled
      service:
        name: docker
        state: started
        enabled: true