---
- name: install docker
  apt:
    name: docker.io
    state: present
    update_cache: true

- name: install docker compose plugin
  apt:
    name: docker-compose-plugin
    state: present
    update_cache: true

- name: ensure docker service is running and enabled
  service:
    name: docker
    state: started
    enabled: true
